@startuml Campane
actor Utente
participant main
entity datiCondivisi

Utente -> main ++ : start

main -> datiCondivisi ** : new
main -> thVisualizza ** : new
main -> thVisualizza ++ : start
main -> Din ** : new
main -> Din ++ : start
main -> Don ** : new

loop while(true)
Din -> datiCondivisi: semLetto.Wait()
Din -> datiCondivisi: mutex.Wait()
Din -> datiCondivisi: incDin()
Din -> datiCondivisi: mutex.Signal()
Din -> datiCondivisi: semScritto.Signal()

thVisualizza -> datiCondivisi: semScritto.Wait()
thVisualizza -> Utente: Din
thVisualizza -> datiCondivisi: semLetto.Signal()
end

main -> Don ++ : start
loop while(true)
Don -> datiCondivisi: semLetto.Wait()
Don -> datiCondivisi: mutex.Wait()
Don -> datiCondivisi: incDon()
Don -> datiCondivisi: mutex.Signal()
Don -> datiCondivisi: semScritto.Signal()

thVisualizza -> datiCondivisi: semScritto.Wait()
thVisualizza -> Utente: Don
thVisualizza -> datiCondivisi: semLetto.Signal()
end

main -> Dan ** : new
main -> Dan ++: start

loop while(true)
Dan -> datiCondivisi: semLetto.Wait()
Dan -> datiCondivisi: mutex.Wait()
Dan -> datiCondivisi: incDan()
Dan -> datiCondivisi: mutex.Signal()
Dan -> datiCondivisi: semScritto.Signal()

thVisualizza -> datiCondivisi: semScritto.Wait()
thVisualizza -> Utente: Dan
thVisualizza -> datiCondivisi: semLetto.Signal()
end

Utente -> main: preme tasto
main -> Din: interrupt()
main -> Don: interrupt()
main -> Dan: interrupt()
main -> thVisualizza: interrupt()

Din -> main --: return
note over main : join Din
Dan -> main --: return
Don -> main --: return
note over main : join Don
note over main : join Dan



thVisualizza -> main --: return
note over main : join thVisualizza
@enduml